theme: minima
title: FreeFall
description: Current downloads have not been tested due to a fried Arduino Mega 2560. Sorry for the inconvenience!
minima:
 header_pages:
  - Installation/index.md
  - Downloads/index.md
